// app reducer
export const CHANGE_VIEW = "CHANGE_VIEW";
export const REDIRECT_TO_BUDGET = "REDIRECT_TO_BUDGET";
export const REDIRECT_TO_REPORTS = "REDIRECT_TO_REPORTS";
export const REDIRECT_TO_ACCOUNTS = "REDIRECT_TO_ACCOUNTS";

// budget reducer
export const CREATE_CATEGORY = "CREATE_CATEGORY";